Fix TestJetStreamClusterHardKillAfterStreamAdd
Prevents walking purged directory causing:

```
=== RUN   TestJetStreamClusterHardKillAfterStreamAdd
  jetstream_cluster_4_test.go:3913: require no error, but got: open $SYS/_js_/S-R3F-3UlxOL47/__msgs__: no such file or directory
--- FAIL: TestJetStreamClusterHardKillAfterStreamAdd (0.51s)
```

Signed-off-by: Waldemar Quevedo <wally@nats.io>