Should not have added domain to the StreamInfo returned by stream creation as it breaks one of the existing JS test:
```
    jetstream_cluster_2_test.go:998: Expected to have NO domain set but got "SPOKE"
--- FAIL: TestJetStreamClusterDomainsWithNoJSHub (1.32s)
```

Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>